// LegalKit Disclaimers - These MUST appear on every generated document and site-wide

export const DISCLAIMERS = {
  documentHeader: `⚠️ IMPORTANT DISCLAIMER: This document was generated by LegalKit, an automated template generator. It does NOT constitute legal advice. LegalKit is a template generator, not a law firm. Consult a qualified attorney before using this document in production.`,
  
  documentFooter: `--- 
DISCLAIMER: This document was automatically generated by LegalKit (legalkit.vercel.app) and is provided as a template only. Generated documents are templates and do not constitute legal advice. LegalKit is a template generator, not a law firm. You should consult a qualified attorney licensed in your jurisdiction before using any generated document for your business. Use of this template is at your own risk. LegalKit, its creators, and affiliates accept no liability for any consequences arising from the use of generated documents.`,

  siteFooter: `LegalKit is a template generator, not a law firm. Generated documents are templates and do not constitute legal advice. Consult a qualified attorney before using in production.`,

  siteBanner: `⚠️ LegalKit generates document templates only — not legal advice. Always consult a qualified attorney.`,

  pdfWatermark: `TEMPLATE - NOT LEGAL ADVICE - Generated by LegalKit`,
} as const;

export const LIABILITY_NOTICE = `
BY USING LEGALKIT, YOU ACKNOWLEDGE AND AGREE THAT:

1. LegalKit is an automated document template generator, NOT a law firm and NOT a substitute for legal counsel.
2. All generated documents are templates and do NOT constitute legal advice.
3. You must consult a qualified attorney licensed in your jurisdiction before using any generated document.
4. LegalKit, Deep End Ventures, and their affiliates accept NO LIABILITY for any consequences arising from the use of generated documents.
5. Generated documents may not comply with all applicable laws in your jurisdiction.
6. You are solely responsible for ensuring any document you use complies with applicable laws and regulations.
`;
